const eventConfig={eventName:"Experts in Computing – New Term Event",venue:"Currys Academy, Fort Dunlop",feedback:{welcome:"https://forms.office.com/Pages/ResponsePage.aspx?id=replace-welcome-feedback",supplier:"https://forms.office.com/Pages/ResponsePage.aspx?id=replace-supplier-feedback",overall:"https://forms.office.com/Pages/ResponsePage.aspx?id=replace-overall-feedback"}};
const eventDays=["Monday 13th July 2026","Tuesday 14th July 2026","Wednesday 15th July 2026","Thursday 16th July 2026","Friday 17th July 2026"];
const sessions={welcome:{title:"Welcome & event briefing",room:"Main Academy",type:"Plenary"},break1:{title:"Morning break",room:"Breakout area",type:"Break"},lunch:{title:"Lunch",room:"Breakout area",type:"Break"},break2:{title:"Afternoon break",room:"Breakout area",type:"Break"},close:{title:"Wrap up & final feedback",room:"Main Academy",type:"Plenary"},logitech:{title:"Logitech",room:"Room 1",type:"Supplier"},gigabyte:{title:"Gigabyte",room:"Room 2",type:"Supplier"},msi:{title:"MSI",room:"Room 3",type:"Supplier"},asus:{title:"ASUS",room:"Room 4",type:"Supplier"},acer:{title:"Acer",room:"Room 5",type:"Supplier"},norton:{title:"Norton",room:"Room 6",type:"Supplier"},funnivation:{title:"Funnivation",room:"Room 7",type:"Supplier"},glorious:{title:"Glorious",room:"Room 8",type:"Supplier"},intel:{title:"Intel",room:"Room 9",type:"Supplier"}};
const timeSlots=[{time:"09:15 - 09:50",fixed:"welcome"},{time:"10:00 - 10:25"},{time:"10:30 - 10:55"},{time:"11:00 - 11:25"},{time:"11:30 - 11:45",fixed:"break1"},{time:"11:50 - 12:15"},{time:"12:20 - 12:45"},{time:"12:45 - 13:30",fixed:"lunch"},{time:"13:35 - 14:00"},{time:"14:05 - 14:30"},{time:"14:35 - 15:00",fixed:"break2"},{time:"15:05 - 15:30"},{time:"15:35 - 16:00"},{time:"16:10 - 16:45",fixed:"close"}];
const rotations={"Group 1 - The RGB Elites":["logitech","gigabyte","msi","asus","acer","norton","funnivation","glorious","intel"],"Group 2 - The RTX Raiders":["gigabyte","msi","asus","acer","norton","funnivation","glorious","intel","logitech"],"Group 3 - CTRL+ALT+WIN":["msi","asus","acer","norton","funnivation","glorious","intel","logitech","gigabyte"],"Group 4 - The Loading Screens":["asus","acer","norton","funnivation","glorious","intel","logitech","gigabyte","msi"],"Group 5 - The Keyboard Warriors":["acer","norton","funnivation","glorious","intel","logitech","gigabyte","msi","asus"],"Group 6 - The 8-bit Bandits":["norton","funnivation","glorious","intel","logitech","gigabyte","msi","asus","acer"],"Group 7 - The Respawn Rangers":["funnivation","glorious","intel","logitech","gigabyte","msi","asus","acer","norton"],"Group 8 - DLC":["glorious","intel","logitech","gigabyte","msi","asus","acer","norton","funnivation"]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let deferredPrompt=null;let chosenDay=localStorage.getItem("eic-day")||"";let chosenGroup=localStorage.getItem("eic-group")||"";
function populate(select,values){select.innerHTML='<option value="">Please select</option>'+values.map(v=>`<option value="${v}">${v}</option>`).join("")}
populate($("#daySelect"),eventDays);populate($("#groupSelect"),Object.keys(rotations));$("#daySelect").value=chosenDay;$("#groupSelect").value=chosenGroup;
setTimeout(()=>$("#splash").classList.add("hide"),650);
function navigate(view){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-nav]').forEach(b=>{if(b.closest('.bottom-nav'))b.classList.toggle('active',b.dataset.nav===view)});window.scrollTo({top:0,behavior:'smooth'});if(view==='day')renderDay()}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
$("#lookupForm").addEventListener("submit",e=>{e.preventDefault();chosenDay=$("#daySelect").value;chosenGroup=$("#groupSelect").value;localStorage.setItem("eic-day",chosenDay);localStorage.setItem("eic-group",chosenGroup);toast("Your timetable has been saved");navigate("day")});
$("#changeSelection").addEventListener("click",()=>navigate("home"));
function buildTimetable(group){let i=0;return timeSlots.map(slot=>{const key=slot.fixed||rotations[group][i++];return{...slot,...sessions[key],sessionKey:key}})}
function parseTime(dateLabel,range,end=false){const dateMap={"Monday 13th July 2026":"2026-07-13","Tuesday 14th July 2026":"2026-07-14","Wednesday 15th July 2026":"2026-07-15","Thursday 16th July 2026":"2026-07-16","Friday 17th July 2026":"2026-07-17"};const part=range.split(" - ")[end?1:0];return new Date(`${dateMap[dateLabel]}T${part}:00`)}
function feedbackUrl(s){if(s.sessionKey==='welcome')return eventConfig.feedback.welcome;if(s.sessionKey==='close')return eventConfig.feedback.overall;if(s.type==='Supplier'){const p=new URLSearchParams({session:s.title,group:chosenGroup,eventDay:chosenDay});return `${eventConfig.feedback.supplier}&${p}`}return null}
function renderDay(){if(!chosenDay||!chosenGroup){$("#dayEmpty").classList.remove("hidden");$("#dayContent").classList.add("hidden");return}$("#dayEmpty").classList.add("hidden");$("#dayContent").classList.remove("hidden");$("#dayGroup").textContent=chosenGroup;$("#dayDate").textContent=chosenDay;const now=new Date();const timetable=buildTimetable(chosenGroup);let completed=0,current=null;$("#timeline").innerHTML=timetable.map(s=>{const start=parseTime(chosenDay,s.time),end=parseTime(chosenDay,s.time,true);const done=now>end;const active=now>=start&&now<=end;if(done)completed++;if(active)current=s;const url=feedbackUrl(s);return `<article class="session-card ${s.type.toLowerCase()} ${done?'done':''} ${active?'current':''}">${active?'<span class="status-dot"></span>':''}<div class="time-block">${s.time.split(' - ')[0]}<small>${s.time.split(' - ')[1]}</small></div><div><span class="session-kind">${active?'Happening now · ':''}${s.type}</span><h3>${s.title}</h3><p class="session-meta">${s.room}</p>${url?`<a class="feedback-link" href="${url}" target="_blank" rel="noopener">Give feedback →</a>`:''}</div></article>`}).join('');const percent=Math.round(completed/timetable.length*100);$("#progressBar").style.width=`${percent}%`;$("#progressText").textContent=`${percent}%`;if(current){$("#nowCard").classList.remove("hidden");$("#nowCard").innerHTML=`<span class="now-label">Happening now</span><h3>${current.title}</h3><p>${current.room} · until ${current.time.split(' - ')[1]}</p>`}else $("#nowCard").classList.add("hidden")}
const supplierKeys=Object.keys(sessions).filter(k=>sessions[k].type==='Supplier');$("#supplierGrid").innerHTML=supplierKeys.map(k=>`<article class="supplier-card"><div class="supplier-monogram">${sessions[k].title.slice(0,2).toUpperCase()}</div><div><strong>${sessions[k].title}</strong><small>${sessions[k].room}</small></div></article>`).join('');$("#locationList").innerHTML=supplierKeys.map(k=>`<article class="location-card"><span class="room-number">${sessions[k].room.replace('Room ','')}</span><div><strong>${sessions[k].room}</strong><small>${sessions[k].title} session</small></div></article>`).join('');
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$("#installButton").classList.remove('hidden')});$("#installButton").addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installButton").classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
